In [15]:
import pandas as pd
import numpy as np
import random

In [16]:
#dane - informacje o pogodzie
outlook=['Sunny','Sunny','Overcast','Rainy','Rainy','Rainy','Overcast','Sunny','Sunny','Rainy','Sunny','Overcast','Overcast','Rainy']
temp=['Hot','Hot','Hot','Mild','Cool','Cool','Cool','Mild','Cool','Mild','Mild','Mild','Hot','Mild']

#etykiety - czy pogoda jest odpowiednia na grę w tenisa?
play=['No','No','Yes','Yes','Yes','No','Yes','No','Yes','Yes','Yes','Yes','Yes','No']

Konwersja **danych kategorycznych** do **danych numerycznych**:



In [17]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()

#Sunny-2,Rainy-1,Overcast-0

outlook_encoded=le.fit_transform(outlook)
temp_encoded=le.fit_transform(temp)

print(outlook_encoded)
print(temp_encoded)

[2 2 0 1 1 1 0 2 2 1 2 0 0 1]
[1 1 1 2 0 0 0 2 0 2 2 2 1 2]


# Nowa sekcja

Konersja etykiet do **danych numerycznych**:

In [18]:
#No-0,Yes-1

label=le.fit_transform(play)
print(label)

[0 0 1 1 1 0 1 0 1 1 1 1 1 0]


Outlook + temp

In [19]:
data=list(zip(outlook_encoded,temp_encoded))
print(data)

[(2, 1), (2, 1), (0, 1), (1, 2), (1, 0), (1, 0), (0, 0), (2, 2), (2, 0), (1, 2), (2, 2), (0, 2), (0, 1), (1, 2)]


In [20]:
from sklearn.neighbors import KNeighborsClassifier

In [21]:
dataFile = pd.read_csv('tenis.csv')

In [22]:
dataFile.head()

Day   Outlook Temperature Humidity    Wind PlayTennis
0  D1     Sunny         Hot     High    Weak         No
1  D2     Sunny         Hot     High  Strong         No
2  D3  Overcast         Hot     High    Weak        Yes
3  D4      Rain        Mild     High    Weak        Yes
4  D5      Rain        Cool   Normal    Weak        Yes

A

In [23]:
from sklearn.neighbors import KNeighborsClassifier

neigh = KNeighborsClassifier(n_neighbors=3)
neigh.fit(data,label)

point = np.array([[2,2]])

print(neigh.predict(point))

[0]


C

In [26]:
outlook =  list(dataFile["Outlook"])
print(outlook)

['Sunny', 'Sunny', 'Overcast', 'Rain', 'Rain', 'Rain', 'Overcast', 'Sunny', 'Sunny', 'Rain', 'Sunny', 'Overcast', 'Overcast', 'Rain']


In [27]:
temperature =  list(dataFile["Temperature"])
print(temperature)

['Hot', 'Hot', 'Hot', 'Mild', 'Cool', 'Cool', 'Cool', 'Mild', 'Cool', 'Mild', 'Mild', 'Mild', 'Hot', 'Mild']


In [29]:
humidity =  list(dataFile["Humidity"])
print(humidity)

['High', 'High', 'High', 'High', 'Normal', 'Normal', 'Normal', 'High', 'Normal', 'Normal', 'Normal', 'High', 'Normal', 'High']


In [30]:
wind =  list(dataFile["Wind"])
print(wind)

['Weak', 'Strong', 'Weak', 'Weak', 'Weak', 'Strong', 'Strong', 'Weak', 'Weak', 'Weak', 'Strong', 'Strong', 'Weak', 'Strong']


In [31]:
play =  list(dataFile["PlayTennis"])
print(play)

['No', 'No', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No']


In [33]:
outlook_encoded=le.fit_transform(outlook)
temp_encoded=le.fit_transform(temperature)
humidity_encoded=le.fit_transform(humidity)
wind_encoded=le.fit_transform(wind)

In [34]:
data=list(zip(outlook_encoded,temp_encoded,humidity_encoded,wind_encoded))
print(data)

[(2, 1, 0, 1), (2, 1, 0, 0), (0, 1, 0, 1), (1, 2, 0, 1), (1, 0, 1, 1), (1, 0, 1, 0), (0, 0, 1, 0), (2, 2, 0, 1), (2, 0, 1, 1), (1, 2, 1, 1), (2, 2, 1, 0), (0, 2, 0, 0), (0, 1, 1, 1), (1, 2, 0, 0)]


In [35]:
label=le.fit_transform(play)
print(label)

[0 0 1 1 1 0 1 0 1 1 1 1 1 0]


In [36]:
neigh = KNeighborsClassifier(n_neighbors=3)
neigh.fit(data,label)

point = np.array([[2,0,0,0]])

print(neigh.predict(point))

[0]
